services:

  discovery_events-server:
    build: ./discoveryEvents-service
    container_name: discovery_events-server
    ports:
      - "7077:7077"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=discovery_events-db
      - DB_NAME=discovery_events
      - DB_USER=postgres
      - DB_PASSWORD=123
    depends_on:
      - discovery_events-db



  discovery_events-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=discovery_events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5434:5432"