services:

  discovery_events-server:
    build: ./discoveryEvents-service
    container_name: discovery_events-server
    ports:
      - "7077:7077"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=discovery_events-db
      - DB_NAME=discovery_events
      - DB_USER=postgres
      - DB_PASSWORD=123
    depends_on:
      - discovery_events-db



  discovery_events-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=discovery_events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5434:5432"



  stats-service-server:
    build: ./stats-service-api
    container_name: stats-service-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=stats-db
      - DB_NAME=stats
      - DB_USER=postgres
      - DB_PASSWORD=123
    depends_on:
      - stats-db

  stats-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5431"