server:
  port: 7077

spring:
  application:
    name: discoveryEvents-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:discovery_events-db}:5432/${DB_NAME:discovery_events}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

