server:
  port: 9090

spring:
  application:
    name: stats-service-api


    datasource:
      url: jdbc:postgresql://${DB_HOST:stats-db}:5431/${DB_NAME:stats}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:123}

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true